Repository QCrBox/QCrBox, pull requests merged in 2024-04, with the labels that each got.

#193 Fix expired Discord invites in docs
  docs/how_to_guides/use_qcb_to_interact_with_and_manage_qcrbox.md
  docs/index.md
Labels: documentation, discord

#182 Install markdown-exec with [ansi] extras
  docs/CHANGELOG.md
  docs/how_to_guides/use_qcb_to_interact_with_and_manage_qcrbox.md
  qcrbox/pyproject.toml
  qcrbox/requirements-all.txt
  qcrbox/requirements-client.txt
  qcrbox/requirements-dev.txt
  qcrbox/requirements-docs.txt
  qcrbox/requirements-server.txt
  qcrbox/requirements.txt
Labels: bug, documentation

#184 Add CrysalisPro and Wine Baseimage from QuBox repository
  .env.dev
  .gitignore
  docker-compose.build.yml
  docs/tutorials/examples/example_crysalis_pro.ipynb
  qcrbox_wrapper/qcrbox_wrapper/qcrbox_wrapper.py
  services/applications/crysalis-pro/.idesktop/crysalispro.lnk
  services/applications/crysalis-pro/.idesktop/rigaku_oxford_diffraction_logo.png
  services/applications/crysalis-pro/Dockerfile
  services/applications/crysalis-pro/config_crysalis-pro.yaml
  services/applications/crysalis-pro/configure_crysalis-pro.py
  services/applications/crysalis-pro/docker-compose.crysalis-pro.build.yml
  services/applications/crysalis-pro/docker-compose.crysalis-pro.run.yml
  services/applications/crysalis-pro/run_crysalis_pro_setup_if_not_yet_installed.sh
  services/base_images/base_wine/Dockerfile
Labels: crystallographic-application
