Repository QCrBox/QCrBox, pull requests merged in 2024-02, with the labels that each got.

#85 SHELX prebuild script improvements
  .env.dev
  qcrbox/qcrbox/cli/subcommands/build/commands.py
  services/applications/shelx/prebuild__01_download_and_extract_shelx_executables.py
  services/applications/shelx/prebuild__02_verify_shelx_executables.py
  services/applications/shelx/prebuild__verify_shelx_executables.sh
  services/applications/shelx/shelx_download_urls.txt
  services/applications/shelx/shelx_executables/README.md
Labels: windows

#89 Allow each application's docker compose configuration to live in its own subfolder
  .env.dev
  docker-compose.build.yml
  docker-compose.run.yml
  docs/CHANGELOG.md
  qcrbox/qcrbox/cli/helpers/compose_file_config.py
  services/applications/crystal_explorer/docker-compose.build.crystal-explorer.yml
  services/applications/crystal_explorer/docker-compose.run.crystal-explorer.yml
  services/applications/olex2_linux/docker-compose.build.olex2_linux.yml
  services/applications/olex2_linux/docker-compose.run.olex2_linux.yml
  services/applications/shelx/docker-compose.build.shelx.yml
  services/applications/shelx/docker-compose.run.shelx.yml
  services/applications/shelx/prebuild__01_download_and_extract_shelx_executables.py
Labels: refactoring

#94 Application template scaffolding
  .github/workflows/qcrbox-ci.yml
  docs/CHANGELOG.md
  qcrbox/pyproject.toml
  qcrbox/qcrbox/cli/cli.py
  qcrbox/qcrbox/cli/helpers/compose_file_config.py
  qcrbox/qcrbox/cli/subcommands/__init__.py
  qcrbox/qcrbox/cli/subcommands/init.py
  qcrbox/requirements-all.txt
  qcrbox/requirements-dev.txt
  services/applications/_templates/cli_application/cookiecutter.json
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/Dockerfile
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/config_{{cookiecutter.application_slug}}.yaml
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/configure_{{cookiecutter.application_slug}}.py
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/docker-compose.{{cookiecutter.application_slug}}.build.yml
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/docker-compose.{{cookiecutter.application_slug}}.run.yml
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/sample_cmd.sh
Labels: enhancement, docker, CLI, development, crystallographic-application, developer-beta-release

#112 Tweak docker-compose*.yml filename pattern of existing components to match the new template
  qcrbox/qcrbox/cli/helpers/compose_file_config.py
  services/applications/crystal_explorer/docker-compose.crystal-explorer.build.yml
  services/applications/crystal_explorer/docker-compose.crystal-explorer.run.yml
  services/applications/olex2_linux/docker-compose.olex2_linux.build.yml
  services/applications/olex2_linux/docker-compose.olex2_linux.run.yml
  services/applications/shelx/docker-compose.shelx.build.yml
  services/applications/shelx/docker-compose.shelx.run.yml
Labels: bug, CLI

#114 Print guidance for possible next steps after running 'qcb init'
  qcrbox/qcrbox/cli/subcommands/init.py
  services/applications/_templates/cli_application/cookiecutter.json
Labels: CLI

#113 Merge olex2
  .gitignore
  qcrbox/pyproject.toml
  services/applications/olex2_linux/Dockerfile
  services/applications/olex2_linux/config_olex2.yaml
  services/applications/olex2_linux/configure_olex2.py
  services/applications/olex2_linux/docker-compose.olex2_linux.build.yml
  services/applications/olex2_linux/docker-compose.olex2_linux.run.yml
  services/applications/olex2_linux/olex2_glue_cli.py
  services/applications/olex2_linux/prebuild__01_create_olex2_headless.py
  services/applications/olex2_linux/qcrboxtools-0.0.1-py3-none-any.whl
  services/applications/olex2_linux/qcrboxtools.yml
  wrapper/example_olex2.ipynb
Labels: enhancement, crystallographic-application, developer-beta-release

#118 Rename qcb build targets
  qcrbox/qcrbox/cli/subcommands/build.py
Labels: bug

#121 Ruff config / GH Actions
  .github/workflows/qcrbox-ci.yml
  .pre-commit-config.yaml
  qcrbox/pyproject.toml
  qcrbox/qcrbox/cli/helpers/cif_helpers.py
  services/applications/qcrboxtools/qcrbtls_check_convergence_glue.py
  services/applications/qcrboxtools/qcrbtls_replace_structure_glue.py
  services/applications/qcrboxtools/qcrbtls_to_unified_cif_glue.py
  wrapper/qcrbox_wrapper.py
Labels: chore, CI

#125 Add environment variable to configure shared folder path on the host
  .env.dev
  docker-compose.run.yml
  qcrbox/qcrbox/cli/helpers/docker_project.py
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/docker-compose.{{cookiecutter.application_slug}}.run.yml
  services/applications/crystal_explorer/docker-compose.crystal-explorer.run.yml
  services/applications/eval1x/docker-compose.eval1x.run.yml
  services/applications/olex2_linux/docker-compose.olex2_linux.run.yml
  services/applications/qcrboxtools/docker-compose.qcrboxtools.run.yml
  services/applications/shelx/docker-compose.shelx.run.yml
  services/applications/shelx/prebuild__01_download_and_extract_shelx_executables.py
Labels: enhancement, configuration
