Repository QCrBox/QCrBox, pull requests merged in 2024-03, with the labels that each got.

#133 Git setting: normalise line endings
  .gitattributes
  docs/CHANGELOG.md
  wrapper/qcrbox_wrapper.py
Labels: bug, developer-release, windows

#129 Olex2 example and Wrapper Improvements
  .gitignore
  services/applications/olex2_linux/config_olex2.yaml
  services/applications/olex2_linux/configure_olex2.py
  services/applications/olex2_linux/olex2_glue_cli.py
  services/applications/xharpy_gpaw/configure_xharpy-gpaw.py
  wrapper/example_eval.ipynb
  wrapper/example_olex2.ipynb
  wrapper/example_olex2.toparams_stub.ipynb
  wrapper/input_files/example.tscb
Labels: developer-release

#147 Add Guide how to convert CIF Files in QCrBox
  docs/how_to_guides/contents.md
  docs/how_to_guides/handle_cifs.md
Labels: documentation, developer-release

#149 Add External command tutorial
  docs/tutorials/contents.md
  docs/tutorials/example_support/cif2cellcheckcsd.sh
  docs/tutorials/wrap_external_command.md
Labels: documentation, developer-release

#151 Basic outline for a README
  README.md
  docs/CHANGELOG.md
Labels: documentation, developer-release

#153 Changelog updates
  README.md
  docs/CHANGELOG.md
Labels: documentation, developer-release

#155 Add intro paragraph to docs landing page
  docs/.pages
  docs/index.md
  docs/qcrbox_custom_styling.css
  mkdocs.yml
Labels: documentation, developer-release

#159 Integrate example Jupyter notebooks into docs
  .github/workflows/qcrbox-ci.yml
  README.md
  docs/.pages
  docs/ADRs/.pages
  docs/CHANGELOG.md
  docs/background_info/.pages
  docs/how_to_guides/.pages
  docs/how_to_guides/set_up_a_dev_environment.md
  docs/index.md
  docs/technical_reference/.pages
  docs/tutorials/.pages
  docs/tutorials/contents.md
  docs/tutorials/examples/.pages
  docs/tutorials/examples/example_crystal_explorer.ipynb
  docs/tutorials/examples/example_eval.ipynb
  docs/tutorials/examples/example_olex2.ipynb
  docs/tutorials/examples/example_olex2.toparams_stub.ipynb
  docs/tutorials/examples/example_qcrboxtools.ipynb
  docs/tutorials/examples/example_xharpy.ipynb
  docs/tutorials/wrap_external_command.md
  docs/tutorials/wrap_python_command.md
  mkdocs.yml
  qcrbox/pyproject.toml
  qcrbox/requirements-all.txt
  qcrbox/requirements-client.txt
  qcrbox/requirements-dev.txt
  qcrbox/requirements-docs.txt
  qcrbox/requirements-server.txt
  qcrbox/requirements.txt
Labels: documentation, CI

#161 Install qcrbox during docs build
  .github/workflows/qcrbox-ci.yml
  qcrbox/pyproject.toml
  qcrbox/qcrbox/cli/helpers/qcrbox_helpers.py
  qcrbox/requirements-all.txt
  qcrbox/requirements-client.txt
  qcrbox/requirements-dev.txt
  qcrbox/requirements-docs.txt
  qcrbox/requirements-server.txt
  qcrbox/requirements.txt
Labels: bug, documentation, CI, developer-release

#165 Add options --enable/--disable to `qcb` to allow more fine-grained builds
  docs/CHANGELOG.md
  qcrbox/qcrbox/cli/cli.py
  qcrbox/qcrbox/cli/helpers/__init__.py
  qcrbox/qcrbox/cli/helpers/cli_helpers.py
  qcrbox/qcrbox/cli/subcommands/build.py
  qcrbox/qcrbox/cli/subcommands/up.py
  qcrbox/qcrbox/logging.py
Labels: enhancement, CLI, developer-release

#166 Misc fixes
  docker-compose.build.yml
  docker-compose.run.yml
  qcrbox/qcrbox/cli/helpers/docker_project.py
  qcrbox/qcrbox/cli/subcommands/build.py
  qcrbox/qcrbox/cli/subcommands/up.py
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/docker-compose.{{cookiecutter.application_slug}}.build.yml
  services/applications/_templates/cli_application/{{cookiecutter.application_slug}}/docker-compose.{{cookiecutter.application_slug}}.run.yml
  services/applications/crystal_explorer/docker-compose.crystal-explorer.build.yml
  services/applications/crystal_explorer/docker-compose.crystal-explorer.run.yml
  services/applications/crystal_explorer/prebuild__01_download_crystal_explorer.py
  services/applications/eval1x/docker-compose.eval1x.build.yml
  services/applications/eval1x/docker-compose.eval1x.run.yml
  services/applications/olex2_linux/docker-compose.olex2_linux.build.yml
  services/applications/olex2_linux/docker-compose.olex2_linux.run.yml
  services/applications/olex2_linux/prebuild__01_create_olex2_headless.py
  services/applications/qcrboxtools/docker-compose.qcrboxtools.build.yml
  services/applications/qcrboxtools/docker-compose.qcrboxtools.run.yml
  services/applications/shelx/docker-compose.shelx.build.yml
  services/applications/shelx/docker-compose.shelx.run.yml
  services/applications/xharpy_gpaw/docker-compose.xharpy-gpaw.build.yml
  services/applications/xharpy_gpaw/docker-compose.xharpy-gpaw.run.yml
Labels: bug

#169 Docs enhancements
  README.md
  docs/how_to_guides/set_up_a_dev_environment.md
  docs/index.md
  docs/qcrbox_custom_styling.css
  mkdocs.yml
Labels: documentation, developer-release

#171 Fix qcb silent errors
  .env.dev
  qcrbox/qcrbox/cli/helpers/docker_project.py
  qcrbox/qcrbox/cli/helpers/doit_helpers.py
  qcrbox/qcrbox/cli/helpers/qcrbox_helpers.py
Labels: bug, CLI, developer-release

#173 Fix command registration
  docs/CHANGELOG.md
  qcrbox/pyproject.toml
  qcrbox/qcrbox/registry/client/client.py
  qcrbox/qcrbox/registry/client/registered_application_client_side.py
  qcrbox/qcrbox/registry/server/server.py
Labels: bug, inventory

#174 Fix windows build
  docs/CHANGELOG.md
  qcrbox/qcrbox/cli/helpers/__init__.py
  qcrbox/qcrbox/cli/helpers/docker_project.py
  qcrbox/qcrbox/cli/helpers/qcrbox_helpers.py
  qcrbox/qcrbox/cli/subcommands/build.py
Labels: bug, CLI, windows

#175 Ensure all command arguments passed to subprocess.run() are strings
  qcrbox/qcrbox/cli/subcommands/build.py
Labels: bug

#176 Capture subprocess output to be able to report it in case of errors
  qcrbox/qcrbox/cli/subcommands/build.py
Labels: development

#162 Moved example files to examples, updated wrapper
  .gitignore
  docs/tutorials/examples/example_crystal_explorer.ipynb
  docs/tutorials/examples/example_eval.ipynb
  docs/tutorials/examples/example_olex2.ipynb
  docs/tutorials/examples/example_olex2.toparams_stub.ipynb
  docs/tutorials/examples/example_qcrboxtools.ipynb
  docs/tutorials/examples/example_xharpy.ipynb
  docs/tutorials/examples/input_files/difference_test1.cif
  docs/tutorials/examples/input_files/difference_test2.cif
  docs/tutorials/examples/input_files/example.tscb
  docs/tutorials/examples/input_files/input.cif
  docs/tutorials/examples/input_files/iso2aniso.cif
  docs/tutorials/examples/input_files/non_unified_kws.cif
  docs/tutorials/examples/qcrbox_wrapper.py
Labels: documentation, developer-release

#180 Bump QCrBox version
  docs/CHANGELOG.md
  docs/how_to_guides/set_up_a_dev_environment.md
Labels: developer-release

#181 How-to guide on using qcb to build and run components
  docs/CHANGELOG.md
  docs/how_to_guides/.pages
  docs/how_to_guides/contents.md
  docs/how_to_guides/use_qcb_to_interact_with_and_manage_qcrbox.md
Labels: documentation, CLI, developer-release
